apiVersion: batch/v1
kind: Job
metadata:
  name: uugai-cli-generate-default-labels
spec:
  template:
    spec:
      containers:
      - name: init-container
        image: uugai/cli:latest
        command: ['/main', '-action', 'generate-default-labels',
          '-mongodb-uri', 'mongodb+srv://<username>:<password>@<host>/<database>?retryWrites=true&w=majority&appName=<appName>',
          #'-mongodb-host', '<host>',
          #'-mongodb-port', '27017',
          #'-mongodb-username', '<username>',
          #'-mongodb-password', '<password>',
          #'-mongodb-database-credentials', 'admin', 
          '-mongodb-source-database', 'Kerberos',
          '-label-names', 'incident,suspicious,unauthorized', # Comma separated list of labels to generate
          '-mode', 'dry-run', # or live to execute for real.
          #'-username', '<username>', # For adding to a specific user, empty will target all users
        ]
            
      restartPolicy: Never
      volumes:
      - name: hub-import
        emptyDir: {}